// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class LUX_PATCH
    {
        public static class ImageSpace
        {
            private static FormLink<IImageSpaceGetter> Construct(uint id) => new FormLink<IImageSpaceGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IImageSpaceGetter> _LUX_Dungeon_IS => Construct(0x975CF); // Lux_ISUnderground [IMGS:080975CF]
            public static FormLink<IImageSpaceGetter> _LUX_Interior_IS => Construct(0x924B3); // Lux_ISHouses [IMGS:080924B3]

            // public static FormLink<IImageSpaceGetter> _LUX_Test_IS => Construct(0x60ba7);
        }
    }
}
